import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { aiAPI, recipeAPI } from '../services/api';
import { useAuth } from '../context/AuthContext';
import { useLanguage } from '../context/LanguageContext';
import { useToast } from '../context/ToastContext';
import BuyIngredientsModal from '../components/recipe/BuyIngredientsModal';
import KitchenTimer from '../components/recipe/KitchenTimer';
import confetti from 'canvas-confetti';
import {
  Sparkles,
  ChefHat,
  Flame,
  ShieldAlert,
  Save,
  ShoppingBag,
  Clock,
  Users,
  CheckCircle,
  RotateCcw,
  Zap,
  Tag,
  ArrowRight,
} from 'lucide-react';

const AIGenerator = () => {
  const { user, isAuthenticated } = useAuth();
  const { t } = useLanguage();
  const { toast } = useToast();
  const navigate = useNavigate();

  // Generator Inputs
  const [ingredientsInput, setIngredientsInput] = useState('');
  const [allergiesInput, setAllergiesInput] = useState('');
  const [selectedDiet, setSelectedDiet] = useState('Vegetarian');
  const [selectedCuisine, setSelectedCuisine] = useState('Indian');
  const [selectedMealType, setSelectedMealType] = useState('Dinner');
  const [targetCalories, setTargetCalories] = useState(420);
  const [customPrompt, setCustomPrompt] = useState('');

  // Generated Recipe Result State
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedRecipe, setGeneratedRecipe] = useState(null);
  const [isSaving, setIsSaving] = useState(false);
  const [isBuyModalOpen, setIsBuyModalOpen] = useState(false);

  const pantrySuggestions = [
    'Spinach',
    'Paneer',
    'Tomatoes',
    'Garlic',
    'Cumin Seeds',
    'Greek Yogurt',
    'Mushrooms',
    'Basmati Rice',
    'Olive Oil',
    'Lentils',
  ];

  const commonAllergies = ['Peanuts', 'Gluten', 'Dairy', 'Shellfish', 'Soy', 'Eggs', 'Tree Nuts'];

  const handleAddPantryChip = (chip) => {
    const list = ingredientsInput
      ? ingredientsInput.split(',').map((i) => i.trim())
      : [];
    if (!list.includes(chip)) {
      list.push(chip);
      setIngredientsInput(list.join(', '));
    }
  };

  const handleAddAllergyChip = (chip) => {
    const list = allergiesInput
      ? allergiesInput.split(',').map((i) => i.trim())
      : [];
    if (!list.includes(chip)) {
      list.push(chip);
      setAllergiesInput(list.join(', '));
    }
  };

  const handleGenerate = async (e) => {
    e.preventDefault();
    if (!ingredientsInput.trim() && !customPrompt.trim()) {
      toast.error('Please enter at least one ingredient or a prompt');
      return;
    }

    setIsGenerating(true);
    setGeneratedRecipe(null);

    try {
      const res = await aiAPI.generateRecipe({
        ingredients: ingredientsInput,
        allergies: allergiesInput,
        dietary: selectedDiet,
        cuisine: selectedCuisine,
        mealType: selectedMealType,
        targetCalories: Number(targetCalories),
        prompt: customPrompt,
      });

      setGeneratedRecipe(res.data.recipe);
      toast.success('Gourmet recipe generated by AI Chef!');
      confetti({ particleCount: 50, spread: 70, origin: { y: 0.7 } });
    } catch (err) {
      toast.error('Failed to generate recipe. Please retry.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSaveToDatabase = async () => {
    if (!isAuthenticated) {
      toast.info('Please sign in to save recipes to your account');
      navigate('/login');
      return;
    }
    if (!generatedRecipe) return;

    setIsSaving(true);
    try {
      const res = await recipeAPI.create({
        ...generatedRecipe,
        isAIGenerated: true,
      });
      toast.success('Saved to your recipe collection!');
      navigate(`/recipe/${res.data.recipe._id}`);
    } catch (err) {
      toast.error('Failed to save recipe to database');
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-12">
      {/* Studio Banner */}
      <div className="text-center max-w-3xl mx-auto space-y-4">
        <div className="flex flex-wrap items-center justify-center gap-2">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-amber-500/10 border border-amber-500/30 text-amber-900 dark:text-amber-300 text-xs font-bold shadow-xs">
            <Sparkles className="w-4 h-4 text-amber-500" />
            <span>Intelligent Culinary Synthesis & Allergy Safety</span>
          </div>
          {/* OpenRouter GPT-4o Badge */}
          <div className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-emerald-50 dark:bg-emerald-950/40 border border-emerald-300 dark:border-emerald-800 text-emerald-800 dark:text-emerald-300 text-[11px] font-bold shadow-xs">
            <Zap className="w-3.5 h-3.5 text-emerald-500" />
            <span>Powered by GPT-4o via OpenRouter</span>
          </div>
        </div>
        <h1 className="text-3xl sm:text-5xl font-serif font-extrabold text-forest-900 dark:text-cream-50">
          {t('aiStudioTitle', 'AI Culinary Studio')}
        </h1>
        <p className="text-xs sm:text-sm text-stone-600 dark:text-stone-300 leading-relaxed">
          {t(
            'aiStudioSubtitle',
            'Tell our AI Chef what ingredients you have in your pantry and any allergies to avoid. We will craft a bespoke, gourmet recipe instantly!'
          )}
        </p>
      </div>

      {/* Main Grid: Form Inputs (Left) & Generated Live Preview (Right) */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        {/* FORM INPUTS (5 COLS) */}
        <div className="lg:col-span-5 bg-white dark:bg-[#0e271f] p-6 sm:p-8 rounded-3xl border border-stone-200 dark:border-forest-800 shadow-soft space-y-6">
          <form onSubmit={handleGenerate} className="space-y-5">
            {/* Ingredients Field */}
            <div className="space-y-2">
              <label className="block text-xs font-bold text-stone-800 dark:text-stone-200 flex items-center justify-between">
                <span>{t('availableIngredients', 'Available Pantry Ingredients *')}</span>
                <span className="text-[10px] text-stone-400">Comma separated</span>
              </label>
              <textarea
                rows={3}
                required
                placeholder={t('ingredientsPlaceholder', 'e.g. spinach, paneer, tomatoes, garlic, cumin, heavy cream')}
                value={ingredientsInput}
                onChange={(e) => setIngredientsInput(e.target.value)}
                className="w-full px-3.5 py-2.5 rounded-2xl bg-stone-50 dark:bg-forest-950/70 border border-stone-200 dark:border-forest-800 text-xs text-stone-800 dark:text-stone-100 focus:outline-none focus:border-gold-500"
              />

              {/* Quick chip suggestions */}
              <div className="flex flex-wrap gap-1.5 pt-1">
                {pantrySuggestions.map((item) => (
                  <button
                    key={item}
                    type="button"
                    onClick={() => handleAddPantryChip(item)}
                    className="text-[10px] font-semibold px-2 py-0.5 rounded-md bg-stone-100 dark:bg-forest-950 hover:bg-gold-100 dark:hover:bg-gold-950 text-stone-600 dark:text-stone-300 border border-stone-200 dark:border-forest-800 transition-colors"
                  >
                    + {item}
                  </button>
                ))}
              </div>
            </div>

            {/* Allergies & Exclusions */}
            <div className="space-y-2">
              <label className="block text-xs font-bold text-stone-800 dark:text-stone-200 flex items-center gap-1.5 text-rose-600 dark:text-rose-400">
                <ShieldAlert className="w-3.5 h-3.5" />
                <span>{t('allergiesLabel', 'Allergies / Ingredients to strictly avoid')}</span>
              </label>
              <input
                type="text"
                placeholder={t('allergiesPlaceholder', 'e.g. peanuts, gluten, dairy, shellfish')}
                value={allergiesInput}
                onChange={(e) => setAllergiesInput(e.target.value)}
                className="w-full px-3.5 py-2.5 rounded-2xl bg-stone-50 dark:bg-forest-950/70 border border-stone-200 dark:border-forest-800 text-xs focus:outline-none focus:border-rose-400"
              />

              <div className="flex flex-wrap gap-1.5 pt-1">
                {commonAllergies.map((all) => (
                  <button
                    key={all}
                    type="button"
                    onClick={() => handleAddAllergyChip(all)}
                    className="text-[10px] font-semibold px-2 py-0.5 rounded-md bg-rose-50 dark:bg-rose-950/40 hover:bg-rose-100 text-rose-700 dark:text-rose-300 border border-rose-200 dark:border-rose-900 transition-colors"
                  >
                    🚫 {all}
                  </button>
                ))}
              </div>
            </div>

            {/* Diet & Cuisine */}
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="block text-xs font-bold text-stone-700 dark:text-stone-300 mb-1">
                  {t('dietPreferenceLabel', 'Dietary Preference')}
                </label>
                <select
                  value={selectedDiet}
                  onChange={(e) => setSelectedDiet(e.target.value)}
                  className="w-full p-2.5 rounded-xl bg-stone-50 dark:bg-forest-950 border border-stone-200 dark:border-forest-800 text-xs"
                >
                  {['Vegetarian', 'Vegan', 'High-Protein', 'Gluten-Free', 'Keto', 'Low-Calorie', 'Any'].map((d) => (
                    <option key={d} value={d}>{d}</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-xs font-bold text-stone-700 dark:text-stone-300 mb-1">
                  {t('cuisineChoiceLabel', 'Preferred Cuisine')}
                </label>
                <select
                  value={selectedCuisine}
                  onChange={(e) => setSelectedCuisine(e.target.value)}
                  className="w-full p-2.5 rounded-xl bg-stone-50 dark:bg-forest-950 border border-stone-200 dark:border-forest-800 text-xs"
                >
                  {['Indian', 'Italian', 'Mexican', 'Asian', 'Mediterranean', 'American'].map((c) => (
                    <option key={c} value={c}>{c}</option>
                  ))}
                </select>
              </div>
            </div>

            {/* Meal Type & Target Calories */}
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="block text-xs font-bold text-stone-700 dark:text-stone-300 mb-1">
                  {t('mealTypeLabel', 'Meal Category')}
                </label>
                <select
                  value={selectedMealType}
                  onChange={(e) => setSelectedMealType(e.target.value)}
                  className="w-full p-2.5 rounded-xl bg-stone-50 dark:bg-forest-950 border border-stone-200 dark:border-forest-800 text-xs"
                >
                  {['Dinner', 'Lunch', 'Breakfast', 'Snack', 'Dessert'].map((m) => (
                    <option key={m} value={m}>{m}</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-xs font-bold text-stone-700 dark:text-stone-300 mb-1">
                  Target Calories
                </label>
                <input
                  type="number"
                  min="150"
                  max="1200"
                  step="50"
                  value={targetCalories}
                  onChange={(e) => setTargetCalories(e.target.value)}
                  className="w-full p-2.5 rounded-xl bg-stone-50 dark:bg-forest-950 border border-stone-200 dark:border-forest-800 text-xs"
                />
              </div>
            </div>

            {/* Custom Notes */}
            <div className="space-y-1">
              <label className="block text-xs font-bold text-stone-700 dark:text-stone-300">
                {t('specialPromptLabel', 'Special Requests / Health Goals (Optional)')}
              </label>
              <input
                type="text"
                placeholder={t('specialPromptPlaceholder', 'e.g. 15-minute quick recovery meal, crispy texture')}
                value={customPrompt}
                onChange={(e) => setCustomPrompt(e.target.value)}
                className="w-full px-3.5 py-2.5 rounded-2xl bg-stone-50 dark:bg-forest-950/70 border border-stone-200 dark:border-forest-800 text-xs focus:outline-none focus:border-gold-500"
              />
            </div>

            {/* Submit Button */}
            <button
              type="submit"
              disabled={isGenerating}
              className="w-full flex items-center justify-center gap-2 py-3.5 rounded-2xl bg-forest-900 text-cream-50 dark:bg-gold-500 dark:text-forest-950 font-bold text-xs sm:text-sm shadow-md hover:scale-[1.02] transition-all disabled:opacity-50"
            >
              <Sparkles className="w-4 h-4" />
              <span>{isGenerating ? 'Chef is Crafting Recipe...' : t('generateRecipeBtn', 'Generate Gourmet Recipe')}</span>
            </button>
          </form>
        </div>

        {/* GENERATED RECIPE PREVIEW (7 COLS) */}
        <div className="lg:col-span-7 space-y-6">
          {isGenerating ? (
            <div className="p-16 rounded-3xl bg-white dark:bg-[#0e271f] border border-stone-200 dark:border-forest-800 shadow-soft text-center space-y-4">
              <div className="w-16 h-16 rounded-3xl bg-forest-900 text-gold-400 flex items-center justify-center mx-auto animate-bounce shadow-md">
                <ChefHat className="w-8 h-8" />
              </div>
              <h3 className="font-serif font-bold text-xl text-forest-900 dark:text-cream-50">
                Formulating Allergy-Safe Recipe...
              </h3>
              <p className="text-xs text-stone-500 max-w-sm mx-auto">
                Analyzing pantry synergy, flavor pairings, and balancing calories.
              </p>
            </div>
          ) : generatedRecipe ? (
            <div className="p-6 sm:p-8 rounded-3xl bg-white dark:bg-[#0e271f] border border-gold-500/40 shadow-card space-y-6 animate-scaleUp">
              {/* Recipe Top Header */}
              <div className="flex flex-col sm:flex-row items-start justify-between gap-4 pb-4 border-b border-stone-100 dark:border-forest-900">
                <div>
                  <div className="flex items-center gap-2 mb-2 flex-wrap">
                    <span className="text-[10px] font-extrabold uppercase px-2.5 py-1 rounded-full bg-gold-500 text-forest-950 shadow-xs flex items-center gap-1">
                      <Sparkles className="w-3 h-3" /> AI Masterpiece
                    </span>
                    {generatedRecipe.aiModel && (
                      <span className="text-[10px] font-bold px-2.5 py-1 rounded-full bg-emerald-100 dark:bg-emerald-950/50 text-emerald-800 dark:text-emerald-300 border border-emerald-300 dark:border-emerald-800 flex items-center gap-1">
                        <Zap className="w-3 h-3" />
                        {generatedRecipe.aiModel}
                      </span>
                    )}
                    <span className="text-xs font-bold text-forest-800 dark:text-gold-400">
                      {generatedRecipe.cuisine} • {generatedRecipe.category}
                    </span>
                  </div>
                  <h2 className="text-2xl sm:text-3xl font-serif font-bold text-forest-900 dark:text-cream-50">
                    {generatedRecipe.title}
                  </h2>
                </div>

                <div className="flex items-center gap-2 shrink-0">
                  <button
                    onClick={() => setIsBuyModalOpen(true)}
                    className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-amber-400 hover:bg-amber-500 text-stone-950 font-bold text-xs shadow-xs transition-transform hover:scale-105"
                  >
                    <ShoppingBag className="w-3.5 h-3.5" />
                    <span>Buy Ingredients</span>
                  </button>
                  <button
                    onClick={handleSaveToDatabase}
                    disabled={isSaving}
                    className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-forest-900 text-cream-50 dark:bg-gold-500 dark:text-forest-950 font-bold text-xs shadow-xs hover:scale-105 transition-all"
                  >
                    <Save className="w-3.5 h-3.5" />
                    <span>{isSaving ? 'Saving...' : 'Save Recipe'}</span>
                  </button>
                </div>
              </div>

              <p className="text-xs sm:text-sm text-stone-600 dark:text-stone-300 leading-relaxed italic">
                "{generatedRecipe.description}"
              </p>

              {/* Chef Tip from GPT-4o */}
              {generatedRecipe.chefTip && (
                <div className="flex items-start gap-3 p-3.5 rounded-2xl bg-amber-50 dark:bg-amber-950/30 border border-amber-200 dark:border-amber-900">
                  <ChefHat className="w-5 h-5 text-amber-600 dark:text-amber-400 shrink-0 mt-0.5" />
                  <div>
                    <p className="text-[11px] font-extrabold uppercase text-amber-700 dark:text-amber-400 mb-0.5">Chef GPT-4o Tip</p>
                    <p className="text-xs text-amber-900 dark:text-amber-200 leading-relaxed">{generatedRecipe.chefTip}</p>
                  </div>
                </div>
              )}

              {/* Specs & Nutrition */}
              <div className="grid grid-cols-4 gap-2 text-center text-xs">
                <div className="p-2.5 rounded-2xl bg-stone-50 dark:bg-forest-950/70 border border-stone-200 dark:border-forest-900">
                  <p className="text-[10px] text-stone-400 font-bold">PREP</p>
                  <p className="font-bold text-forest-900 dark:text-cream-50">{generatedRecipe.prepTime} min</p>
                </div>
                <div className="p-2.5 rounded-2xl bg-stone-50 dark:bg-forest-950/70 border border-stone-200 dark:border-forest-900">
                  <p className="text-[10px] text-stone-400 font-bold">COOK</p>
                  <p className="font-bold text-forest-900 dark:text-cream-50">{generatedRecipe.cookTime} min</p>
                </div>
                <div className="p-2.5 rounded-2xl bg-stone-50 dark:bg-forest-950/70 border border-stone-200 dark:border-forest-900">
                  <p className="text-[10px] text-stone-400 font-bold">CALORIES</p>
                  <p className="font-bold text-gold-600 dark:text-gold-400">{generatedRecipe.nutritionFacts?.calories} kcal</p>
                </div>
                <div className="p-2.5 rounded-2xl bg-stone-50 dark:bg-forest-950/70 border border-stone-200 dark:border-forest-900">
                  <p className="text-[10px] text-stone-400 font-bold">PROTEIN</p>
                  <p className="font-bold text-forest-900 dark:text-cream-50">{generatedRecipe.nutritionFacts?.protein}g</p>
                </div>
              </div>

              {/* Ingredients */}
              <div className="space-y-3">
                <h3 className="font-serif font-bold text-base text-forest-900 dark:text-cream-50">
                  Ingredients Generated
                </h3>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                  {generatedRecipe.ingredients?.map((ing, i) => (
                    <div
                      key={i}
                      className="p-2.5 rounded-xl bg-stone-50 dark:bg-forest-950/50 border border-stone-200 dark:border-forest-900 text-xs flex items-center justify-between"
                    >
                      <span className="font-semibold text-stone-900 dark:text-stone-100">{ing.name}</span>
                      <span className="font-bold text-gold-600 dark:text-gold-400 font-mono">
                        {ing.quantity} {ing.unit}
                      </span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Step-by-Step Instructions with timer widgets */}
              <div className="space-y-4 pt-2">
                <h3 className="font-serif font-bold text-base text-forest-900 dark:text-cream-50">
                  Step-by-Step Instructions
                </h3>
                <div className="space-y-3">
                  {generatedRecipe.instructions?.map((inst, i) => (
                    <div
                      key={i}
                      className="p-4 rounded-2xl bg-stone-50 dark:bg-forest-950/70 border border-stone-200 dark:border-forest-900 space-y-2"
                    >
                      <div className="flex items-center justify-between">
                        <span className="font-bold text-xs text-gold-600 dark:text-gold-400">
                          Step {inst.stepNumber}: {inst.title}
                        </span>
                      </div>
                      <p className="text-xs text-stone-700 dark:text-stone-300 leading-relaxed">
                        {inst.text}
                      </p>
                      {inst.timerMinutes > 0 && (
                        <div className="max-w-xs pt-1">
                          <KitchenTimer
                            initialMinutes={inst.timerMinutes}
                            stepTitle={`Step ${inst.stepNumber} Timer`}
                            onComplete={() => toast.success(`Step ${inst.stepNumber} completed!`)}
                          />
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>

              <BuyIngredientsModal
                isOpen={isBuyModalOpen}
                onClose={() => setIsBuyModalOpen(false)}
                ingredients={generatedRecipe.ingredients}
                recipeTitle={generatedRecipe.title}
              />
            </div>
          ) : (
            <div className="p-16 rounded-3xl bg-white dark:bg-[#0e271f] border border-dashed border-stone-300 dark:border-forest-800 text-center space-y-4">
              <div className="w-16 h-16 rounded-3xl bg-stone-100 dark:bg-forest-950 flex items-center justify-center mx-auto text-stone-400">
                <Sparkles className="w-8 h-8 text-gold-500" />
              </div>
              <h3 className="font-serif font-bold text-xl text-forest-900 dark:text-cream-50">
                Your AI Kitchen Awaits
              </h3>
              <p className="text-xs text-stone-500 max-w-sm mx-auto">
                Fill in your available ingredients on the left and click Generate to see your personalized gourmet recipe here!
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default AIGenerator;
